-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 12 oct. 2021 à 16:08
-- Version du serveur : 10.4.20-MariaDB
-- Version de PHP : 7.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `numeric_history`
--

-- --------------------------------------------------------

--
-- Structure de la table `personnage`
--

CREATE TABLE `personnage` (
  `id` int(15) NOT NULL,
  `nom_complet` varchar(255) NOT NULL,
  `nom_image` varchar(255) NOT NULL,
  `historique` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `personnage`
--

INSERT INTO `personnage` (`id`, `nom_complet`, `nom_image`, `historique`) VALUES
(1, 'Alan Turing', 'Alan-Turing.jpg', 'Alan Mathison Turing, né le 23 juin 1912 à Londres et mort le 7 juin 1954 à Wilmslow, est un mathématicien et cryptologue britannique, auteur de travaux qui fondent scientifiquement l\'informatique.\r\n\r\nPour résoudre le problème fondamental de la décidabilité en arithmétiques, il présente en 1936 une expérience de pensée que l\'on nommera ensuite machine de Turing et des concepts de programme et de programmation, qui prendront tout leur sens avec la diffusion des ordinateurs, dans la seconde moitié du xxe siècle. Son modèle a contribué à établir la thèse de Church, qui définit le concept mathématique intuitif de fonction calculable.\r\n\r\nDurant la Seconde Guerre mondiale, il joue un rôle majeur dans la cryptanalyse de la machine Enigma utilisée par les armées allemandes : l\'invention de machines usant de procédés électroniques , les bombes1, fera passer le décryptage à plusieurs milliers de messages par jour. Ce travail secret ne sera connu du public que dans les années 1970. Après la guerre, il travaille sur un des tout premiers ordinateurs, puis contribue au débat sur la possibilité de l\'intelligence artificielle, en proposant le test de Turing. Vers la fin de sa vie, il s\'intéresse à des modèles de morphogenèse du vivant conduisant aux « structures de Turing ».\r\n\r\nPoursuivi en justice en 1952 pour homosexualité, il choisit, pour éviter la prison, la castration chimique par prise d\'œstrogènes. Il est retrouvé mort par empoisonnement au cyanure le 8 juin 1954 dans la chambre de sa maison à Wilmslow. La reine Élisabeth II le reconnaît comme héros de guerre et le gracie à titre posthume en 2013.'),
(2, 'Gérard Berry', 'Berry.jpg', 'Gérard Berry, né le 25 décembre 1948, est un informaticien français, professeur au Collège de France, membre de l\'Académie des sciences française (depuis 2002), de l\'Académie des technologies (depuis 2005), et de l\'Academia Europaea (depuis 1993).\r\n\r\nGérard Berry est le fils d\'un commissaire de police et d\'une enseignante en mathématiques. Il a deux frères ingénieurs, dont l\'un, Michel Berry, son aîné, l\'a précédé dans le cursus de formation1.\r\n\r\nIl est ancien élève de l\'École polytechnique2,3 et ingénieur général des Mines4,2. Après sa sortie de l\'École des mines de Paris (1973), il reste rémunéré comme chercheur dans cette école jusqu\'en 2000, tout en poursuivant d\'abord une thèse d\'État en mathématiques (soutenue en 1979), puis en poursuivant des projets au sein de l\'Institut national de recherche en informatique et en automatique (INRIA) ou de l\'École des mines, d\'abord à Rocquencourt, puis à Sophia Antipolis. À partir de 1980, son principal axe de recherche est le développement du langage Esterel qui permet d\'exprimer la synchronisation temporelle de tâches et de prouver leur bon déroulement.\r\n\r\nDe 2001 à 2009, il est directeur scientifique d\'Esterel Technologies.\r\n\r\nDe 2009 à août 2012, il est directeur de recherches, en détachement du corps des mines, à l\'INRIA, où il est membre de l\'équipe-projet Indes5 et préside la commission d\'évaluation de la recherche6.\r\n\r\nÀ compter de 2008, Gérard Berry donne des cours au Collège de France, et y dispose, depuis septembre 2012 de la chaire « Algorithmes, machines et langages7 », tout en restant collaborateur extérieur du projet INRIA Indes (cf. supra). Certains de ses cours 2007-2008 et 2009-2010 ont été redonnés en anglais à l\'université d\'Édimbourg dans le cours intitulé « Seven Keys to the Digital Future » en collaboration avec le Collège de France, l\'INRIA et la Royal Society of Edinburgh.\r\n\r\nIl est aussi « Régent » de « Déformatique » au Collège de \'Pataphysique.\r\n\r\nDepuis 2018, il appartient au conseil scientifique de l\'Éducation nationale'),
(3, ' Philippe Dreyfus', 'Philippe-Dreyfus.jpg', 'Philippe Dreyfus, né le 4 novembre 1925 dans le 17ème  arrondissement de Paris et mort le 31 juillet 2018 à Biarritz1, est un pionnier et seul créateur du mot informatique en France.\r\nDiplômé de la 66e promotion de l\'ESPCI ParisTech2, il devient professeur d\'informatique à l\'université Harvard où il participe au développement du premier ordinateur numérique, le Harvard Mark I, puis est nommé directeur du Centre national de calcul électronique de la société Bull dans les années 1950.\r\n\r\nBien qu\'étymologiquement le mot « informatik » fût créé par l\'ingénieur allemand Karl Steinbuch en 1957, il est le premier à utiliser sa traduction française « informatique » dès 19623, par la fondation de la Société d\'informatique appliquée (SIA)4. Le mot informatique désigne alors la contraction des mots information et automatique5,6.\r\n\r\nEn 1965 il est nommé directeur de CAP Europe puis vice-président de Cap-Gemini Sogeti en 19757.\r\n\r\nEn 1990, il est l\'inventeur du terme Informativité.'),
(4, 'Bill Gates', 'Bill-Gates.jpg', 'Bill Gates naît le 28 octobre 1955 à Seattle (État de Washington) aux États-Unis, dans une famille aisée.\r\n\r\nSon père, William Henry Gates II (1925-2020), est avocat d\'affaires. Sa mère, Mary Maxwell Gates, est professeur et présidente de la direction de quelques entreprises et banques de la United Way of America et le First Interstate Bank4,5.\r\n\r\nBill Gates découvre l\'informatique à la très sélective Lakeside School de Seattle, qui dispose alors d\'un PDP-10 loué. Il y réalise avec son ami d\'enfance Paul Allen son premier programme informatique : un jeu de tic-tac-toe (morpion).\r\n\r\nEn 1968, âgé de 13 ans, il fonde avec Allen et quelques autres amis le Lakeside Programmeurs Group. Quelques sociétés recourront à leurs talents, essentiellement pour améliorer des systèmes et des applications existantes écrites en langage assembleur.\r\n\r\nEn 1973, Gates entre à l\'université Harvard, à l\'âge de 18 ans. Il y rencontre Steve Ballmer, futur CEO de Microsoft. Il abandonne rapidement ses études pour se consacrer uniquement à la programmation informatique.\r\n\r\nLe 13 décembre 1977, il est arrêté par la police à Albuquerque au Nouveau-Mexique pour une conduite sans permis. De cette arrestation subsistera une célèbre photographie d\'identité judiciaire où l\'on voit le patron de Microsoft sourire sur les clichés, malgré les circonstances'),
(5, 'Charles Babbage', 'Charles-Babbage.jpg', 'Charles Babbage, né le 26 décembre 1791 et mort le 18 octobre 1871 à Londres, est un polymathe, mathématicien et inventeur visionnaire britannique du XIX ème  siècle qui fut l\'un des principaux précurseurs de l\'informatique.\r\n\r\nIl fut le premier à énoncer le principe d\'un ordinateur. C\'est en 1834, pendant le développement d\'une machine à calculer destinée au calcul et à l\'impression de tables mathématiques (la machine à différences) qu\'il eut l\'idée d\'y incorporer des cartes du métier Jacquard, dont la lecture séquentielle donnerait des instructions et des données à sa machine, et donc imagina l\'ancêtre mécanique des ordinateurs d\'aujourd\'hui. Il n\'acheva jamais sa machine analytique, mais il passa le reste de sa vie à la concevoir dans les moindres détails et à en construire un prototype. Un de ses fils en construisit l\'unité centrale (le moulin) et l\'imprimante en 1888 et fit une démonstration réussie de calcul de table à l\'académie royale d\'astronomie en 19081.\r\n\r\nC\'est entre 1847 et 1849 que Charles Babbage entreprit d\'utiliser les avancées technologiques de sa machine analytique pour concevoir les plans d\'une deuxième machine à différences no 2 qui, à spécifications égales, demandait trois fois moins de pièces que la précédente.\r\n\r\nEn 1991, à partir de ces plans, on a pu reconstruire une partie de cette machine qui fonctionne parfaitement en utilisant les techniques qui étaient disponibles au XIXème siècle ce qui montre qu\'elle aurait pu être construite du vivant de Charles Babbage.'),
(6, 'John von Neumann', 'John-von-Neumann.jpg', 'János Neumann de Margitta (John von Neumann) est né le 28 décembre 1903, à Budapest, en Hongrie. Il était à la fois physicien et mathématicien. Il a contribué dans de nombreux secteurs dont la logique mathématique, la mécanique quantique, l\'économie, l\'armement atomique, etc. Son meilleur don et la manière dont il contribua à tant de domaines furent sa capacité à prendre une idée qui avaient été laissée puisque personne ne pouvait la continuer et l’avancer. Le jeune génie qui a contribué à l\'invention de l\'ordinateur qui nous semble vitale de nos jours meure du cancer le 8 février 1957 à Washington.'),
(7, 'Isaac Newton', 'Isaac-Newton.jpg', 'Isaac Newton (25 décembre 1642 J – 20 mars 1727 J, ou 4 janvier 1643 G – 31 mars 1727 G)N 1 est un mathématicien, physicien, philosophe, alchimiste, astronome et théologien anglais, puis britannique. Figure emblématique des sciences, il est surtout reconnu pour avoir fondé la mécanique classique, pour sa théorie de la gravitation universelle et la création, en concurrence avec Gottfried Wilhelm Leibniz, du calcul infinitésimal. En optique, il a développé une théorie de la couleur basée sur l\'observation selon laquelle un prisme décompose la lumière blanche en un spectre visible. Il a aussi inventé le télescope à réflexion composé d\'un miroir primaire concave appelé télescope de Newton.\r\n\r\nEn mécanique, il a établi les trois lois universelles du mouvement qui constituent en fait des principes à la base de la grande théorie de Newton concernant le mouvement des corps, théorie que l\'on nomme aujourd\'hui « mécanique newtonienne » ou encore « mécanique classique ».\r\n\r\nIl est aussi connu pour la généralisation du théorème du binôme et l\'invention dite de la méthode de Newton permettant de trouver des approximations d\'un zéro (ou racine) d\'une fonction réelle d\'une variable réelle.\r\n\r\nNewton a montré que les mouvements des objets sur Terre et des corps célestes sont gouvernés par les mêmes lois naturelles ; en se basant sur les lois de Kepler sur le mouvement des planètes1, il développa la loi universelle de la gravitation.\r\n\r\nSon ouvrage Philosophiae naturalis principia mathematica2,3, publié en 1687, est considéré comme une œuvre majeure dans l\'histoire des sciences. C\'est dans celui-ci qu\'il décrit la loi universelle de la gravitation, formule les trois lois universelles du mouvement et jette les bases de la mécanique classique. Il a aussi effectué des recherches dans les domaines de la théologie et de l\'alchimie.'),
(8, 'Alexander Graham Bell', 'Alexander-Graham-Bell.jpg', 'Alexander Graham Bell, enseignant aux personnes sourdes, inventeur, scientifique (né le 3 mars 1847 à Édimbourg, en Écosse; décédé le 2 août 1922 près de Baddeck, en Nouvelle-Écosse). Parmi les grands inventeurs des 19e et 20e siècles, on considère que seul Thomas Alva Edison surpasse Alexander Graham Bell. Bien qu’il soit surtout célèbre pour son invention du téléphone, il a permis d’innover dans de nombreux autres domaines tels que l’aéronautique, les hydroptères et la communication sans fil (le « photophone »). Selon Alexander Graham Bell lui-même, c’est toutefois son travail auprès des personnes sourdes qui demeure sa plus importante contribution. Né en Écosse, il émigre au Canada en 1870 avec ses parents. Il épouse Mabel Hubbard, une Américaine, en 1877, et est naturalisé citoyen américain en 1882. À partir du milieu des années 1880, il passe tous ses étés près de Baddeck, sur l’île du Cap-Breton, avec sa famille. Ils y font bâtir une grande demeure, qu’ils baptisent « Beinn Bhreagh ». À partir de ce moment, Alexander Graham Bell partage son temps et ses recherches entre les États-Unis et le Canada. Il meurt à Baddeck en 1922 et y est enterré.'),
(9, 'Louis Pouzin', 'Louis-Pouzin.jpg', 'Louis Pouzin est un ingénieur français en informatique né le 20 avril 1931 à Chantenay-Saint-Imbert (Nièvre) dans une famille modeste1. Il a créé et développé au début des années 1970 le Réseau Cyclades, à base de datagramme pur, et a contribué au développement des réseaux à commutation de paquets, précurseurs d\'Internet. Ses travaux, et ceux de ses collaborateurs du projet Cyclades Hubert Zimmermann, Gérard Le Lann et Michel Elie, ont eu une influence reconnue par Vint Cerf dans une de ses premières spécifications du protocole de transport d\'Internet TCP.'),
(10, 'Lewis-howard-latimer', 'lewis-howard-latimer.jpg', 'Lewis H. Latimer, né le 4 septembre 1848 à Chelsea, dans le Massachusetts, est le cadet des quatre enfants de George et Rebecca Latimer. George Latimer travailla comme esclave pour divers propriétaires en Virginie jusqu\'à la fin de 1842, quelques mois après avoir épousé Rebecca Smith. Le jeune couple décide de fuir vers les États abolitionnistes au nord de la ligne Mason-Dixon pour sortir de l\'esclavage et assurer à leurs enfants de meilleures conditions de vie.'),
(11, 'HeinrichHertz', 'Heinrich-Hertz.jpg', 'Heinrich Hertz, né le 22 février 1857 à Hambourg et mort le 1er janvier 1894 à Bonn, est un ingénieur et physicien allemand renommé pour avoir découvert les ondes hertziennes auxquelles il a donné son nom.\r\n\r\nC\'est en son honneur que l\'unité internationale de fréquence (s-1) a été appelée hertz (Hz).'),
(12, 'Albert Einstein', 'Albert-Einstein.jpg', 'Albert Einstein (prononcé en allemand [ˈalbɐt ˈaɪnʃtaɪn] Écouter) né le 14 mars 1879 à Ulm, dans le Wurtemberg (Empire allemand), et mort le 18 avril 1955 à Princeton, dans le New Jersey (États-Unis), est un physicien théoricien. Il fut successivement allemand, apatride (entre 1896 et 1901), suisse (1901) et de double nationalité helvético-américaine (1940)N 1. Il épousa Mileva Marić, puis sa cousine Elsa Einstein.\r\n\r\nIl publie sa théorie de la relativité restreinte en 1905 et sa théorie de la gravitation, dite relativité générale, en 1915. Il contribue largement au développement de la mécanique quantique et de la cosmologie, et reçoit le prix Nobel de physique de 1921 pour son explication de l’effet photoélectriqueN 2. Son travail est notamment connu du grand public pour l’équation E=mc2, qui établit une équivalence entre la masse et l’énergie d’un système.\r\n\r\nIl est aujourd\'hui considéré comme l\'un des plus grands scientifiques de l\'histoire, et sa renommée dépasse largement le milieu scientifique. Il est la personnalité du xxe siècle selon l\'hebdomadaire Time. Dans la culture populaire, son nom et sa personne sont directement liés aux notions d\'intelligence, de savoir et de génie.');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `personnage`
--
ALTER TABLE `personnage`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `personnage`
--
ALTER TABLE `personnage`
  MODIFY `id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
